# Generated by Django 3.2.12 on 2022-04-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('font_app', '0002_about_blog_portfolio_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('message', models.TextField(max_length=200)),
                ('adress', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('nin', models.IntegerField()),
                ('bvn', models.IntegerField()),
                ('next_of_kin', models.CharField(max_length=20)),
                ('marital_status', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='content',
            field=models.TextField(max_length=100),
        ),
    ]
