# Generated by Django 3.2.12 on 2022-04-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('font_app', '0003_auto_20220408_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='content',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='services',
            name='content',
            field=models.TextField(max_length=100),
        ),
    ]
