# Generated by Django 3.2.12 on 2022-04-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('font_app', '0004_auto_20220411_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/pics'),
        ),
    ]
