# Generated by Django 3.2.12 on 2022-04-13 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('font_app', '0006_auto_20220413_1008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='my_team',
            new_name='Team',
        ),
    ]
