# Generated by Django 3.2.12 on 2022-04-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('font_app', '0007_rename_my_team_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='content',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='title',
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_content',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(max_length=100),
        ),
    ]
